const dishCuisineMap = {
    "almond": ["Mediterranean", "Middle Eastern", "Desserts"],
    "amaranth": ["Mexican", "Healthy Food", "Vegetarian"],
    "anchovy": ["Mediterranean", "Italian", "Spanish"],
    "antipasto": ["Italian"],
    "apple": ["American", "Desserts", "British"],
    "apple pie": ["American", "Desserts"],
    "apple sauce": ["American", "British"],
    "apricot": ["Middle Eastern", "Mediterranean", "Desserts"],
    "artichoke": ["Mediterranean", "Italian", "French"],
    "arugula": ["Italian", "Mediterranean", "Salad"],
    "asparagus": ["French", "Mediterranean", "Healthy Food"],
    "aspic": ["French", "Russian"],
    "avocado": ["Mexican", "Healthy Food", "American"],
    "baby back ribs": ["American", "BBQ"],
    "bacon": ["American", "British", "Breakfast"],
    "bagel": ["American", "Jewish", "Breakfast"],
    "baguette": ["French"],
    "baked alaska": ["American", "Desserts"],
    "baklava": ["Middle Eastern", "Turkish", "Greek"],
    "bamboo shoots": ["Asian", "Chinese", "Japanese"],
    "banana": ["Caribbean", "Desserts", "Healthy Food"],
    "barley": ["European", "Healthy Food", "Soup"],
    "basil": ["Italian", "Mediterranean", "Thai"],
    "bass": ["Mediterranean", "Seafood"],
    "bay leaf": ["Mediterranean", "Indian", "French"],
    "beancurd": ["Chinese", "Japanese", "Vegetarian"],
    "beans": ["Mexican", "Brazilian", "Healthy Food"],
    "beef": ["American", "Argentine", "BBQ"],
    "beef carpaccio": ["Italian", "French"],
    "beef steak": ["American", "Argentine", "Steak"],
    "beef tartare": ["French", "European"],
    "beet": ["Eastern European", "Healthy Food", "Salad"],
    "beet salad": ["Eastern European", "Healthy Food", "Salad"],
    "beignets": ["French", "Desserts"],
    "bell pepper": ["Mediterranean", "Mexican", "Healthy Food"],
    "berry": ["American", "Desserts", "Healthy Food"],
    "bibimbap": ["Korean"],
    "bilberry": ["European", "Desserts"],
    "birthday cake": ["American", "Desserts"],
    "biscuits": ["American", "Southern", "British"],
    "bitter melon": ["Asian", "Chinese", "Indian"],
    "black beans": ["Mexican", "Brazilian", "Healthy Food"],
    "black currant": ["European", "Desserts"],
    "blackberry": ["American", "Desserts", "Healthy Food"],
    "blood orange": ["Mediterranean", "Desserts"],
    "blood sausage": ["European", "British", "Spanish"],
    "blue cheese": ["French", "American", "Salad"],
    "blueberry": ["American", "Desserts", "Healthy Food"],
    "blueberry pie": ["American", "Desserts"],
    "bok choy": ["Chinese", "Asian", "Healthy Food"],
    "bonbon": ["French", "Desserts"],
    "boysenberry": ["American", "Desserts"],
    "bread": ["European", "Mediterranean", "American"],
    "bread pudding": ["British", "Desserts"],
    "bread rolls": ["European", "American"],
    "breadfruit": ["Caribbean", "Polynesian"],
    "breadstick": ["Italian"],
    "bream": ["Mediterranean", "Seafood"],
    "brie": ["French", "Cheese"],
    "brioche": ["French", "Breakfast"],
    "brisket": ["American", "BBQ", "Jewish"],
    "brittle": ["American", "Desserts"],
    "broad beans": ["Mediterranean", "Middle Eastern"],
    "broccoli": ["American", "Healthy Food", "Chinese"],
    "broccolini": ["Italian", "Healthy Food"],
    "brown rice": ["Healthy Food", "Asian", "Indian"],
    "brownie": ["American", "Desserts"],
    "brulee": ["French", "Desserts"],
    "bruschetta": ["Italian"],
    "brussels sprout": ["American", "Healthy Food", "European"],
    "buckwheat": ["Russian", "Healthy Food", "Japanese"],
    "burrito": ["Mexican", "Tex-Mex"],
    "butter": ["European", "American", "French"],
    "cabbage": ["European", "Asian", "Healthy Food"],
    "caesar salad": ["American", "Salad"],
    "cake": ["American", "Desserts", "European"],
    "cake pop": ["American", "Desserts"],
    "calamari": ["Mediterranean", "Italian", "Greek"],
    "camembert": ["French", "Cheese"],
    "canape": ["French", "Appetizers"],
    "candy": ["American", "Desserts"],
    "candy apple": ["American", "Desserts"],
    "candy bar": ["American", "Desserts"],
    "cannoli": ["Italian", "Desserts"],
    "cantaloupe": ["Mediterranean", "Desserts"],
    "caper": ["Mediterranean", "Italian", "French"],
    "caprese salad": ["Italian", "Salad"],
    "caramel apple": ["American", "Desserts"],
    "cardoon": ["Mediterranean", "Italian"],
    "carp": ["Chinese", "Eastern European"],
    "carpaccio": ["Italian", "French"],
    "carrot": ["European", "Healthy Food", "Asian"],
    "carrot cake": ["American", "Desserts"],
    "cashew": ["Indian", "Asian", "Healthy Food"],
    "cassava": ["African", "Brazilian", "Caribbean"],
    "casserole": ["American", "European"],
    "cauliflower": ["Indian", "Healthy Food", "American"],
    "caviar": ["Russian", "French", "Luxury"],
    "celery": ["American", "Healthy Food", "European"],
    "cereal": ["American", "Breakfast"],
    "ceviche": ["Peruvian", "Latin American", "Seafood"],
    "chard": ["Mediterranean", "Healthy Food"],
    "cheddar": ["American", "British", "Cheese"],
    "cheese": ["European", "American", "French"],
    "cheeseburger": ["American", "Fast Food"],
    "cheesecake": ["American", "Desserts"],
    "cherry": ["American", "Desserts", "European"],
    "cherry tomato": ["Mediterranean", "Salad"],
    "chestnut": ["European", "Desserts"],
    "chicken": ["American", "Global"],
    "chicken breast": ["American", "Healthy Food"],
    "chicken curry": ["Indian", "Thai"],
    "chicken leg": ["American", "Global"],
    "chicken wings": ["American", "Fast Food"],
    "chickpeas": ["Middle Eastern", "Indian", "Mediterranean"],
    "chili": ["Mexican", "Tex-Mex"],
    "chili pepper": ["Mexican", "Asian", "Indian"],
    "chips": ["British", "American", "Fast Food"],
    "chives": ["European", "Mediterranean"],
    "chocolate": ["European", "Desserts", "American"],
    "chorizo": ["Spanish", "Mexican"],
    "chowder": ["American", "Seafood"],
    "churros": ["Spanish", "Mexican", "Desserts"],
    "chutney": ["Indian", "British"],
    "ciabatta": ["Italian"],
    "cinnamon roll": ["American", "Desserts"],
    "citron": ["Mediterranean", "Desserts"],
    "citrus": ["Mediterranean", "Desserts"],
    "clam": ["Italian", "Seafood"],
    "clam chowder": ["American", "Seafood"],
    "clementine": ["Mediterranean", "Desserts"],
    "cobbler": ["American", "Desserts"],
    "cockle": ["British", "Seafood"],
    "coconut": ["Thai", "Indian", "Caribbean"],
    "coleslaw": ["American", "Salad"],
    "collards": ["Southern", "American"],
    "common bean": ["Mexican", "Brazilian"],
    "compote": ["French", "Desserts"],
    "cookie": ["American", "Desserts"],
    "corn": ["American", "Mexican"],
    "corn bread": ["American", "Southern"],
    "corn salad": ["American", "Salad"],
    "corned beef": ["Irish", "American"],
    "cornflakes": ["American", "Breakfast"],
    "cottage cheese": ["European", "Healthy Food"],
    "couscous": ["North African", "Mediterranean"],
    "crab": ["American", "Seafood", "Asian"],
    "crab cakes": ["American", "Seafood"],
    "cracker": ["American", "Snacks"],
    "cranberry": ["American", "Desserts"],
    "crayfish": ["Cajun", "Seafood"],
    "creme brulee": ["French", "Desserts"],
    "crepe": ["French", "Desserts"],
    "crescent roll": ["French", "Breakfast"],
    "cress": ["European", "Salad"],
    "crispbread": ["Scandinavian", "Healthy Food"],
    "croissant": ["French", "Breakfast"],
    "croque madame": ["French", "Breakfast"],
    "croquette": ["French", "Japanese"],
    "crouton": ["American", "Salad"],
    "crunch": ["American", "Snacks"],
    "cucumber": ["Mediterranean", "Salad"],
    "cupcake": ["American", "Desserts"],
    "curd": ["Indian", "Desserts"],
    "currant": ["European", "Desserts"],
    "custard": ["British", "Desserts"],
    "cuttlefish": ["Mediterranean", "Seafood"],
    "daikon": ["Japanese", "Asian"],
    "dandelion greens": ["European", "Healthy Food"],
    "danish pastry": ["Danish", "Desserts"],
    "date": ["Middle Eastern", "Desserts"],
    "deviled eggs": ["American", "Appetizers"],
    "dough": ["Global", "Bakery"],
    "doughnut": ["American", "Desserts"],
    "dragonfruit": ["Asian", "Healthy Food"],
    "dried apricot": ["Middle Eastern", "Desserts"],
    "dried fruit": ["Global", "Healthy Food"],
    "drumstick": ["American", "Chicken"],
    "duck": ["Chinese", "French"],
    "dumpling": ["Chinese", "Japanese", "Eastern European"],
    "durian": ["Southeast Asian"],
    "eclair": ["French", "Desserts"],
    "edamame": ["Japanese", "Asian"],
    "eel": ["Japanese", "Asian"],
    "egg": ["Global", "Breakfast"],
    "egg white": ["Healthy Food", "Breakfast"],
    "egg yolk": ["Global", "Breakfast"],
    "eggplant": ["Mediterranean", "Italian", "Middle Eastern"],
    "elderberry": ["European", "Desserts"],
    "endive": ["French", "Salad"],
    "english muffin": ["British", "Breakfast"],
    "escargots": ["French"],
    "falafel": ["Middle Eastern", "Vegetarian"],
    "farfalle": ["Italian"],
    "fava beans": ["Mediterranean", "Middle Eastern"],
    "fiddlehead": ["American", "Healthy Food"],
    "fig": ["Mediterranean", "Desserts"],
    "filet mignon": ["French", "Steak"],
    "fillet of sole": ["French", "Seafood"],
    "fish": ["Global", "Seafood"],
    "fish and chips": ["British", "Fast Food"],
    "flan": ["Spanish", "Desserts"],
    "flatbread": ["Middle Eastern", "Mediterranean"],
    "flatfish": ["European", "Seafood"],
    "florence fennel": ["Italian", "Mediterranean"],
    "focaccia": ["Italian"],
    "foie gras": ["French", "Luxury"],
    "fondue": ["Swiss", "French"],
    "frankfurters": ["American", "Fast Food"],
    "french beans": ["French", "Healthy Food"],
    "french bread": ["French"],
    "french fries": ["American", "Fast Food"],
    "french onion soup": ["French"],
    "french toast": ["American", "Breakfast"],
    "fried calamari": ["Italian", "Mediterranean"],
    "fried egg": ["Global", "Breakfast"],
    "fried rice": ["Chinese", "Asian"],
    "frittata": ["Italian", "Breakfast"],
    "fritter": ["American", "Desserts"],
    "frozen yogurt": ["American", "Desserts"],
    "fruit salad": ["Global", "Healthy Food"],
    "fruitcake": ["British", "Desserts"],
    "fudge": ["American", "Desserts"],
    "fusilli": ["Italian"],
    "galette": ["French", "Desserts"],
    "garlic": ["Global", "Mediterranean"],
    "garlic bread": ["Italian", "American"],
    "garlic chives": ["Asian", "Chinese"],
    "gazpacho": ["Spanish"],
    "gherkin": ["European", "Pickles"],
    "ginger": ["Asian", "Chinese", "Indian"],
    "gnocchi": ["Italian"],
    "goats cheese": ["French", "Mediterranean"],
    "goji berry": ["Chinese", "Healthy Food"],
    "goose": ["European", "French"],
    "gooseberry": ["European", "Desserts"],
    "gorgonzola": ["Italian", "Cheese"],
    "gouda": ["Dutch", "Cheese"],
    "goulash": ["Hungarian", "Eastern European"],
    "gourd": ["Asian", "Indian"],
    "granola": ["American", "Healthy Food"],
    "grape": ["Global", "Desserts"],
    "grapefruit": ["American", "Healthy Food"],
    "greek salad": ["Greek", "Mediterranean"],
    "green bean": ["American", "Healthy Food"],
    "green onion": ["Asian", "Chinese"],
    "grilled cheese sandwich": ["American", "Fast Food"],
    "grits": ["American", "Southern"],
    "ground beef": ["American", "Global"],
    "guacamole": ["Mexican", "Tex-Mex"],
    "guava": ["Caribbean", "Latin American"],
    "gyoza": ["Japanese", "Asian"],
    "gyro": ["Greek", "Mediterranean"],
    "habanero pepper": ["Mexican", "Caribbean"],
    "halibut": ["American", "Seafood"],
    "ham": ["American", "European"],
    "hamburger": ["American", "Fast Food"],
    "hash": ["American", "Breakfast"],
    "hazelnut": ["European", "Desserts"],
    "herring": ["Scandinavian", "Seafood"],
    "honey": ["Global", "Desserts"],
    "honeydew melon": ["Global", "Desserts"],
    "hot dog": ["American", "Fast Food"],
    "huckleberry": ["American", "Desserts"],
    "huevos rancheros": ["Mexican", "Breakfast"],
    "hummus": ["Middle Eastern", "Mediterranean"],
    "ice cream": ["Global", "Desserts", "Ice Cream"],
    "iceberg lettuce": ["American", "Salad"],
    "jackfruit": ["Asian", "Vegetarian"],
    "jalapeno": ["Mexican", "Tex-Mex"],
    "jelly beans": ["American", "Desserts"],
    "jerusalem artichoke": ["American", "Healthy Food"],
    "jicama": ["Mexican", "Latin American"],
    "jordan almonds": ["Middle Eastern", "Desserts"],
    "jujube": ["Chinese", "Asian"],
    "juniper berry": ["European", "Mediterranean"],
    "kale": ["American", "Healthy Food"],
    "kebab": ["Middle Eastern", "Turkish"],
    "kettle corn": ["American", "Snacks"],
    "kidney bean": ["Mexican", "Indian"],
    "kingfish": ["Seafood", "Asian"],
    "kipper": ["British", "Seafood"],
    "kiwi fruit": ["New Zealand", "Healthy Food"],
    "knish": ["Jewish", "Eastern European"],
    "kohlrabi": ["German", "Healthy Food"],
    "kombu": ["Japanese", "Asian"],
    "kumquat": ["Asian", "Desserts"],
    "lamb": ["Middle Eastern", "Mediterranean"],
    "lamb chops": ["Mediterranean", "French"],
    "lamb's lettuce": ["French", "Salad"],
    "lasagna": ["Italian"],
    "lavender": ["French", "Desserts"],
    "leek": ["European", "French"],
    "lemon": ["Global", "Desserts"],
    "lemon peel": ["Global", "Desserts"],
    "lentil": ["Indian", "Mediterranean"],
    "lettuce": ["Global", "Salad"],
    "lima bean": ["American", "Healthy Food"],
    'lobster': ['Mediterranean', 'American', 'Seafood', 'French'],
    'macadamia': ['Tropical', 'Australian', 'Pacific Islands'],
    'macaroni': ['American', 'Italian', 'Mediterranean'],
    'macaron': ['French', 'Bakery', 'Desserts'],
    'mango': ['Tropical', 'Indian', 'Southeast Asian', 'Caribbean'],
    'maple syrup': ['American', 'Breakfast', 'Canadian'],
    'margarine': ['European', 'Healthy Food'],
    'marmalade': ['British', 'European', 'Desserts'],
    'meatloaf': ['American', 'Comfort Food'],
    'melons': ['Tropical', 'American', 'Mediterranean'],
    'mussels': ['Mediterranean', 'Seafood', 'French'],
    'mushroom': ['American', 'European', 'Asian', 'Global'],
    'mushroom soup': ['American', 'French', 'Comfort Food'],
    'nachos': ['Mexican', 'Tex-Mex', 'American'],
    'nectarines': ['American', 'Mediterranean', 'European'],
    'noodles': ['Asian', 'Chinese', 'Japanese', 'Korean'],
    'nutmeg': ['Mediterranean', 'Indian', 'Middle Eastern'],
    'octopus': ['Mediterranean', 'Asian', 'Portuguese'],
    'oysters': ['Mediterranean', 'Seafood', 'French'],
    'pancakes': ['American', 'Breakfast', 'Canadian'],
    'papaya': ['Tropical', 'Caribbean', 'South American'],
    'parmesan': ['Italian', 'Mediterranean', 'European'],
    'parsnip': ['European', 'British', 'Mediterranean'],
    'pastry': ['French', 'European', 'Bakery'],
    'pasta': ['Italian', 'Mediterranean', 'American'],
    'pecans': ['American', 'Southern'],
    'peas': ['American', 'European', 'Mediterranean'],
    'peanut butter': ['American', 'Global', 'Latin American'],
    'peanuts': ['American', 'Asian', 'African'],
    'pears': ['American', 'European', 'Mediterranean'],
    'pecorino': ['Italian', 'Mediterranean'],
    'peppers': ['Mediterranean', 'Mexican', 'Global'],
    'pie': ['American', 'Desserts', 'British'],
    'pineapple': ['Tropical', 'Caribbean', 'South American'],
    'pistachio': ['Mediterranean', 'Middle Eastern', 'Turkish'],
    'pita': ['Middle Eastern', 'Mediterranean'],
    'pizza': ['Italian', 'Mediterranean', 'American'],
    'plum': ['American', 'European', 'Mediterranean'],
    'popcorn': ['American', 'Snacks'],
    'potatoes': ['American', 'European', 'Mediterranean'],
    'potato salad': ['American', 'Southern'],
    'poultry': ['American', 'European', 'Mediterranean'],
    'prawn': ['Mediterranean', 'Seafood', 'Asian'],
    'pretzel': ['German', 'European'],
    'pumpkin': ['American', 'Mediterranean', 'Global'],
    'quinoa': ['South American', 'Healthy Food', 'Andean'],
    'radish': ['European', 'Mediterranean', 'Asian'],
    'ramen': ['Japanese', 'Asian'],
    'ravioli': ['Italian', 'Mediterranean'],
    'rice': ['Asian', 'Indian', 'Mediterranean'],
    'risotto': ['Italian', 'Mediterranean'],
    'roast': ['American', 'European', 'Global'],
    'roast beef': ['American', 'European'],
    'roast chicken': ['American', 'European'],
    'roasted vegetables': ['Mediterranean', 'Healthy Food'],
    'roquefort': ['French', 'European'],
    'salad': ['American', 'Mediterranean', 'Healthy Food'],
    'salmon': ['Mediterranean', 'American', 'Seafood'],
    'salsa': ['Mexican', 'Tex-Mex'],
    'sambal': ['Indonesian', 'Asian'],
    'sashimi': ['Japanese'],
    'sauerbraten': ['German'],
    'sausages': ['European', 'American'],
    'scones': ['British', 'Bakery'],
    'scrambled eggs': ['American', 'Breakfast'],
    'seafood': ['Mediterranean', 'American', 'Caribbean'],
    'seedless': ['Fruit', 'Various'],
    'sesame': ['Asian', 'Middle Eastern'],
    'shrimps': ['Seafood', 'Mediterranean'],
    'shortbread': ['British', 'Bakery'],
    'soup': ['American', 'French', 'Mediterranean'],
    'southern': ['Southern', 'American'],
    'soy': ['Asian', 'Japanese', 'Chinese'],
    'spaghetti': ['Italian'],
    'spices': ['Indian', 'Mediterranean', 'Global'],
    'spinach': ['American', 'Mediterranean'],
    'squash': ['American', 'Mediterranean', 'Global'],
    'steak': ['American', 'French', 'British'],
    'steak sauce': ['American'],
    'sushi': ['Japanese', 'Asian'],
    'sweet potato': ['American', 'Mediterranean'],
    'tacos': ['Mexican', 'Tex-Mex'],
    'tahini': ['Middle Eastern', 'Mediterranean'],
    'tamale': ['Mexican', 'Latin American'],
    'tart': ['French', 'Mediterranean', 'Bakery'],
    'tartare': ['French'],
    'tea': ['British', 'Chinese', 'Indian'],
    'toffee': ['British', 'Desserts'],
    'tuna': ['Mediterranean', 'Seafood'],
    'turkey': ['American', 'European'],
    'vegetables': ['Mediterranean', 'Healthy Food'],
    'walnuts': ['American', 'European'],
    'watermelon': ['Tropical', 'Caribbean', 'Global'],
    'yogurt': ['Mediterranean', 'Indian', 'Greek'],
    'zucchini': ['Mediterranean', 'Italian']
}