const cuisines = [
  "Afghani",
  "African",
  "American",
  "Andhra",
  "Arabian",
  "Argentine",
  "Armenian",
  "Asian",
  "Asian Fusion",
  "Assamese",
  "Australian",
  "Awadhi",
  "BBQ",
  "Bakery",
  "Bar Food",
  "Belgian",
  "Bengali",
  "Beverages",
  "Bihari",
  "Biryani",
  "Brazilian",
  "Breakfast",
  "British",
  "Bubble Tea",
  "Burger",
  "Burmese",
  "Börek",
  "Cafe",
  "Cajun",
  "Canadian",
  "Cantonese",
  "Caribbean",
  "Charcoal Grill",
  "Chettinad",
  "Chinese",
  "Coffee and Tea",
  "Contemporary",
  "Continental",
  "Cuban",
  "Cuisine Varies",
  "Curry",
  "Deli",
  "Desserts",
  "Dim Sum",
  "Diner",
  "Drinks Only",
  "Durban",
  "Döner",
  "European",
  "Fast Food",
  "Filipino",
  "Finger Food",
  "Fish and Chips",
  "French",
  "Fusion",
  "German",
  "Goan",
  "Gourmet Fast Food",
  "Greek",
  "Grill",
  "Gujarati",
  "Hawaiian",
  "Healthy Food",
  "Hyderabadi",
  "Ice Cream",
  "Indian",
  "Indonesian",
  "International",
  "Iranian",
  "Irish",
  "Italian",
  "Izgara",
  "Japanese",
  "Juices",
  "Kashmiri",
  "Kebab",
  "Kerala",
  "Kiwi",
  "Korean",
  "Latin American",
  "Lebanese",
  "Lucknowi",
  "Maharashtrian",
  "Malay",
  "Malaysian",
  "Malwani",
  "Mangalorean",
  "Mediterranean",
  "Mexican",
  "Middle Eastern",
  "Mineira",
  "Mithai",
  "Modern Australian",
  "Modern Indian",
  "Moroccan",
  "Mughlai",
  "Naga",
  "Nepalese",
  "New American",
  "North Eastern",
  "North Indian",
  "Oriya",
  "Pakistani",
  "Parsi",
  "Patisserie",
  "Peranakan",
  "Persian",
  "Peruvian",
  "Pizza",
  "Portuguese",
  "Pub Food",
  "Rajasthani",
  "Ramen",
  "Raw Meats",
  "Restaurant Cafe",
  "Salad",
  "Sandwich",
  "Scottish",
  "Seafood",
  "Singaporean",
  "Soul Food",
  "South African",
  "South American",
  "South Indian",
  "Southern",
  "Southwestern",
  "Spanish",
  "Sri Lankan",
  "Steak",
  "Street Food",
  "Sunda",
  "Sushi",
  "Taiwanese",
  "Tapas",
  "Tea",
  "Teriyaki",
  "Tex-Mex",
  "Thai",
  "Tibetan",
  "Turkish",
  "Turkish Pizza",
  "Vegetarian",
  "Vietnamese",
  "Western",
  "World Cuisine"
];

export default cuisines;